### ISSUE TITLE
Doesnt Build

### ISSUE THREAD

**Issue by shadowbooker** [Julioacarrettoni/SpringyFlowLayoutExample#1]
![screen shot 2013-09-20 at 2 15 40 pm](https://f.cloud.github.com/assets/247888/1182717/aff44f6c-2220-11e3-9be7-55c1eacc53de.png)

**Comment by Julioacarrettoni** [comment]
Are you using latest Xcode?
(It could be the GM or the one on the Mac App Store)

**Comment by shadowbooker** [comment]
I'll try it again tonight on a fresh download. It could be the DP Xcode. I'll need to check. (Commuting ATM)

M
